### ISSUE TITLE
App description on F-Droid is outdated

### ISSUE THREAD

**Issue by Fs00** [slapperwan/gh4a#1171]
For some reason, F-Droid still displays the old description for the app (the one that says that _"the app is still in BETA"_), instead of using the `full_description.txt` file under the `metadata` folder in this repo (as it should).
Maybe there's something to do on F-Droid in order to make it retrieve the description from the repo?

**Comment by smichel17** [comment]
It is actually correct in the droid client, but wrong on the website (https://f-droid.org/packages/com.gh4a/)

I believe the fix is to send a PR removing the description here: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.gh4a.yml

I'll do that's shortly, when I reach a computer.

On January 9, 2022 11:25:24 AM UTC, Francesco Saltori ***@***.***> wrote:
>For some reason, F-Droid still displays the old description for the app (the one that says that _"the app is still in BETA"_), instead of using the `full_description.txt` file under the `metadata` folder in this repo (as it should).
>Maybe there's something to do on F-Droid in order to make it retrieve the description from the repo?
>

-- 
To respect your time, I try to write short, functional emails.

**Comment by smichel17** [comment]
It's a long "shortly" :laughing: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10379

**Comment by smichel17** [comment]
In the merge request, I was asked to also remove the app's "summary" translations on F-Droid, since their policy has changed to store that data in the upstream repos instead, now (e.g. in a fastlane structure).

I have done that in this commit: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10379/diffs?commit_id=6c134bded561f86333625f92e77beba541b3becf

If anyone is interested in adding them here, you can find them in the repo at this commit: https://gitlab.com/fdroid/fdroiddata/-/commit/c97077761202fa4374fac09da70eb32de10a1fca

I may do this myself at some point in the future since it's not *that* much work, but it's super low priority for me right now.

**Comment by Fs00** [comment]
I personally think that porting those translations is not even worth it. They are just translations of "GitHub Client" and the full description is never translated.
It makes more sense to me that someone interested makes a PR which translates both the summary and the full description for a given language (I'd rather not have half-translated things).

**Comment by Fs00** [comment]
Since the issue has been fixed on F-Droid side, I'm going to close this.
Thanks @smichel17!
