### ISSUE TITLE
.mjs file issues

### ISSUE THREAD

**Issue by seirdotexe** [slapperwan/gh4a#1177]
Files that use the `.mjs` extension open in an external window instead of opening in the code editor.

**Comment by Fs00** [comment]
I've understood your report correctly, files like https://github.com/seirdotexe/Angry-Birbs-Deobfuscator/blob/main/deobfuscator.mjs get opened in the browser instead of being opened in the built-in code viewer.
Which Android version are you on? Because I'm on Android 10 and .mjs files are recognized and opened correctly.

**Comment by seirdotexe** [comment]
I'm on Android 11. These files get opened correctly on the official Github app.
