### ISSUE TITLE
More Material Design

### ISSUE THREAD

**Issue by jahirfiquitiva** [slapperwan/gh4a#283]
Hi...

I have been creating Material Design apps for some months (just starting with development) and I have some suggestions to make the app more Material Design.

I really like it right now, but I think it can be improved. It also works really great for me.

If there's no problem for me suggesting these changes, please leave a comment and let me know, and I will do it soon.

Thanks in advance. Awesome work with the app.

**Comment by maniac103** [comment]
Suggestions are never a problem, so just go ahead :) Finding the time to actually do the changes will take some time though. If the suggestions include navigation drawer behaviour, make sure to check out the navigation-reorg branch first.

**Comment by maniac103** [comment]
There also are a few obvious things like letting the app bar scroll to the tabs when scrolling the lists. Implementing this (via the design support library) requires replacing the ListViews with RecyclerViews first though, which is quite a large task due to the sheer amount of different lists we're showing.

**Comment by jahirfiquitiva** [comment]
They are few things actually. (Sorry for late reply).

1. Don't force Roboto fonts. Some people use CyanogenMod and CM Themes, like in my case. And I have changed my device fonts, but it doesn't apply in Octodroid because it forces Roboto. 

2. Tabs height should be toolbar height - 8 dp ... for instance (Toolbar: 56dp, Tabs: 48 dp)

3. Cards margins must be 8 dp:
![screenshot_20160121-182110](https://cloud.githubusercontent.com/assets/10360816/12497942/1a608f86-c06d-11e5-9279-5de4ec333186.png)

4. Align the settings properly:
![screenshot_20160121-181942](https://cloud.githubusercontent.com/assets/10360816/12497949/248e1b2c-c06d-11e5-8524-c5967473d4b8.png)

5. This popup shadow is too dark. Compare it with the toolbar popup menu.
![screenshot_20160121-181904](https://cloud.githubusercontent.com/assets/10360816/12497962/34e35294-c06d-11e5-972f-628cf666e46c.png)

6. Homogeneous content shouldn't be in cards. Make it like the second screenshot.
Reference: http://www.google.com/design/spec/components/cards.html#cards-usage 

![screenshot_20160121-182949](https://cloud.githubusercontent.com/assets/10360816/12497968/3dac20ae-c06d-11e5-85ed-8e6b23739e5b.png)
![components_cards8](https://cloud.githubusercontent.com/assets/10360816/12498022/7b6fb48c-c06d-11e5-85b5-44f09845069e.png)


That's it. Awesome app. Thank you so much. :)

**Comment by maniac103** [comment]
OK, let's tackle them one by one:

- 1 is a tricky one, as the included Roboto fonts serve the purpose of enforcing consistent look of the app for Android versions that don't ship the respective fonts (remember, this app has a min API level of 10). I'll look into avoiding the forced Roboto usage for API levels that have all of the required fonts.
- 2 is correct, will change that
- Where did you get the value in 3. from? I can't find it in the design guidelines, and Google's apps don't use a consistent card margin either (e.g. G+ uses 0dp). Is it just because of consistency to the news feed? If yes, I understand, if no, I'm not sure whether increasing the margins provides any real gain. I'll play with it and see how it'll look.
- 4 is a problem of the library we're using for the preference fragment: https://github.com/kolavar/android-support-v4-preferencefragment/issues/15 ... avoiding using the library would mean killing Gingerbread support, which might also be an option given Gingerbread is < 3% of the Android user base now.
- 5 is the default android.widget.Spinner's popup. Its theme is derived from Widget.AppCompat.Spinner, so from Widget.Material.Spinner on API 21+. Not sure what I am supposed to do there.
- For 6, I carefully considered not using cards for the news feed when introducing the material style, but decided *for* the cards, because from my POV they're heterogenous enough to warrant cards. The different heights and contents are visible in your screenshot already, add in some code push events and it becomes even more obvious. Some Google apps use cards for lists as well (G+ feed, call log of Marshmallow's dialer), so I'm not totally off base there.

**Comment by maniac103** [comment]
The commits above fix 1, 2 and 3; 6 is a wont fix, so only 4 and 5 remain open.

@slapperwan Thoughts on killing Gingerbread support? Maybe do a final 3.8 release off master (with the bug fixes there), nuke GB support together with the preference fragment library and a whole bunch of legacy compat code in the navigation-reorg branch and release that as 3.9?

**Comment by jahirfiquitiva** [comment]
@maniac103 
For the fragment, I have been using this code, which works with design support library, although I'm not sure if that's what you need:
https://gist.github.com/jahirfiquitiva/3cf7efde943c9aa90100

And I wish 6 could be done. I mean. It isn't hard to do. And the app will look better.

Anyways, I just wanted to point, that Google theirselves, don't follow their own guidelines, in any of their apps, or the app iconography.
Every app from Google has a different style of drawer, and its shadow is different in every app.
And that's only one of the things, that I won't mention, but if you check them, you will notice them.

What I mean, is that you should base in Google app, but just guidelines.

Again, 6 is not difficult to do, and will look better, so please implement it. Or at least add an option in settings, if possible.

Anyways, thanks for listening to the suggestions and implementing some of them.

Oh, forgot to mention that toolbar height is different in tablets and some devices, (is 48dp in some, 64 dp in landscape, and so on). So you may want to set the tabs height programatically.

**Comment by maniac103** [comment]
I know 6 is not difficult to do, after all, it's just removal of the card view. For the reasons outlined above I won't do it anyway, though; as I said, I carefully considered it.

**Comment by maniac103** [comment]
Also the current style of the event feed items with the large header on top doesn't work well without cards ... one would need to think of a style that arranges the action information differently for the non-card version to work.

**Comment by jahirfiquitiva** [comment]
Ok understood. Btw, would you mind at least centering user picture properly?

As you see in the screenshot, when the card content is just:
"username starred username/repo"
"1 day ago"

the username picture is not properly centered, and looks bad.

**Comment by jahirfiquitiva** [comment]
(Sorry accidentally closed this)

**Comment by maniac103** [comment]
Yeah, it should probably be top aligned.

**Comment by slapperwan** [comment]
@maniac103 agreed to kill GB support.

**Comment by maniac103** [comment]
@jahirfiquitiva I played with the cards in the news feed, and I think a compromise should be possible.

For comparison, this is the current layout:
![screenshot_20160314-125759](https://cloud.githubusercontent.com/assets/781373/13744100/0078c910-e9e6-11e5-9591-8e6a21820d4e.png)

Your proposed layout:
![screenshot_20160314-125606](https://cloud.githubusercontent.com/assets/781373/13744112/113dd9a2-e9e6-11e5-9976-c6cfc762735b.png)

And how about this (G+ like) layout as a compromise:
![screenshot_20160314-125357](https://cloud.githubusercontent.com/assets/781373/13744147/32760f5e-e9e6-11e5-9590-e83deef59ade.png)

It's not as card like as it is currently, but still makes the items stand apart further from each other than the pure list approach, which I think is needed. Thoughts?

**Comment by jahirfiquitiva** [comment]
What you thought was my proposed layout, actually wasn't

What I proposed was the same cards layout (current) just fixing the margins to actually match the MD specs...

Anyways, what you thought was my proposed layout, actually looks great and clean, even cleaner than the G+ style... So, if I had to choose between the three options, I would definetely go with the second one, or the one you thought was my proposal.

**Comment by maniac103** [comment]
Well, see your first comment with screenshots (Jan 22), item 6 - you _did_ propose a layout without any cards.
But anyway, as I said, I don't really like the lack of visual separation in the version without cards (my screenshot 2), which is why I went with cards in the first place. My question more was directed at whether making the cards extend to the sides (screenshot 3) actually is an improvement over the current style (screenshot 1). IMHO it is, would you agree?

**Comment by jahirfiquitiva** [comment]
@maniac103 

Oh, yeah... It's been so long that I forgot it was my suggestion.

Still, I prefer it over the G+ style. The reason is that the G+ style looks good when the cards are tall enough, like in G+ .. But these cards don't look so good since they are small.

**Comment by maniac103** [comment]
In fact, the material design spec recommends cards for the type of usage we have here: http://www.google.com/design/spec/components/lists.html#lists-usage -> 'If more than three lines of text need to be shown in list tiles, use cards instead.'

We have between 2 (headline + date) and 7 (2-line headline + 4 lines of content + date) lines, and I'm thinking of increasing the content line count even further, which would be useful especially for push events.

I'm open to all suggestions for improving on the news feed item layout though. My gut feeling tells me there must be a better way to present the information currently present in the large headline, but I don't have a concrete idea how that improvement could look like.

**Comment by maniac103** [comment]
I've further refined the look of the event list a little. It now looks like this:

![screenshot_20160315-140542](https://cloud.githubusercontent.com/assets/781373/13778610/2c2a9274-eab7-11e5-93e7-47bf9df44955.png)

I've given the contents of the cards somewhat more emphasis by reducing the title font size, moving out the actor name and allowing more content lines (6 instead of 4).

Comments? (question also goes to @slapperwan and @LeoColomb ;) )

**Comment by jahirfiquitiva** [comment]
@maniac103 

It looks better indeed, just make sure that the top padding is 8dp ...and the space between the cards too... and the cards elevation just 2dp...

**Comment by slapperwan** [comment]
I like the separation of the author and the contents, looks much cleaner for me.

**Comment by maniac103** [comment]
@jahirfiquitiva Top padding and card margins already are 8dp (bottom padding is 12dp, it looked a little narrow with 8dp), and card elevation is 2dp. G+ seems to use 1dp card elevation, but that didn't look nice when I tried. I wonder whether I should try 1.5dp...

**Comment by maniac103** [comment]
Fixed the settings paddings with commit 534fb419dba7bc3cddf0b7cf422d2af36ec81769. I think we can safely call this issue fixed now :)
