### ISSUE TITLE
App crashes when scrolling too fast

### ISSUE THREAD

**Issue by devdrops** [slapperwan/gh4a#291]
I've discovered this bug recently on my Samsung Win. When scrolling too fast on a list of files, list of followers etc, the app suddenly crashes and stop.

**Comment by devdrops** [comment]
Also in the most recent time this bug happened, I've sent the error report from my phone :wink:

**Comment by maniac103** [comment]
@devdrops You have a Samsung Galaxy Win?

**Comment by devdrops** [comment]
Yep. I've noticed this problem in my smartphone.
Em 29/02/2016 11:06, "maniac103" <notifications@github.com> escreveu:

**Comment by devdrops** [comment]
BTW it's a Samsung Galaxy Win model GT-I8552B.

**Comment by maniac103** [comment]
OK, just wanted to make sure I'm looking at the right report. Unfortunately I haven't been able to track down this bug so far; but it'll be fixed implicitly when the navigation-reorg branch is merged back because we aren't using the offending code there anymore (we're using RecyclerViews instead of ListViews now).

**Comment by devdrops** [comment]
Ok, thanks for the feedback! :wink:

**Comment by maniac103** [comment]
navigation-reorg merged back to master -> fixed
