### ISSUE TITLE
Opening a repository crashes the app

### ISSUE THREAD

**Issue by Kurre** [slapperwan/gh4a#303]
App crashes when I try to open this repo: https://github.com/mojotech/jeet

Logcat: http://pastebin.com/vwa2c4pX

Using latest debug version of the app.

Just ask if more information is needed :)

**Comment by ARoiD** [comment]
03-24 07:43:26.596 11193 11270 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
03-24 07:43:26.596 11193 11270 E AndroidRuntime: Process: com.gh4a, PID: 11193
03-24 07:43:26.596 11193 11270 E AndroidRuntime: Theme: themes:{}
03-24 07:43:26.596 11193 11270 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: width and height must be > 0
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:830)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:776)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at com.github.mobile.util.ImageUtils.renderSvgToBitmap(ImageUtils.java:153)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at com.github.mobile.util.HttpImageGetter.getDrawable(HttpImageGetter.java:406)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at android.text.HtmlToSpannedConverter.startImg(Html.java:641)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at android.text.HtmlToSpannedConverter.handleStartTag(Html.java:527)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at android.text.HtmlToSpannedConverter.startElement(Html.java:768)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at org.ccil.cowan.tagsoup.Parser.push(Parser.java:795)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1062)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at org.ccil.cowan.tagsoup.Parser.stagc(Parser.java:1017)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:624)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:450)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at android.text.HtmlToSpannedConverter.convert(Html.java:449)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at android.text.Html.fromHtml(Html.java:136)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at com.github.mobile.util.HtmlUtils.encode(HtmlUtils.java:297)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at com.github.mobile.util.HttpImageGetter$ImageGetterAsyncTask.doInBackground(HttpImageGetter.java:354)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at com.github.mobile.util.HttpImageGetter$ImageGetterAsyncTask.doInBackground(HttpImageGetter.java:344)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-24 07:43:26.596 11193 11270 E AndroidRuntime: 	... 3 more

**Comment by maniac103** [comment]
Yep, confirmed, probably a broken/unsupported SVG image.
