### ISSUE TITLE
links to github files tree do not load correctly

### ISSUE THREAD

**Issue by jmue** [slapperwan/gh4a#316]
Links like this [GitHub Java API](https://github.com/maniac103/egit-github/tree/master/org.eclipse.egit.github.core)  do not load correctly within Octodroid.

**Comment by maniac103** [comment]
I am aware of that, but am not sure how to fix it. The problem is the disambiguation between branch and file/path, given branch names can contain slashes as well. Consider those two links:

https://github.com/maniac103/egit-github/tree/master/org.eclipse.egit.github.core
https://github.com/CyanogenMod/android_packages_apps_Settings/tree/stable/cm-13.0-ZNH2K/src/com/android

I'm not sure how Github does that in the backend.

**Comment by maniac103** [comment]
Actually the intermediate activity works just fine. Will use that approach.
