### ISSUE TITLE
[Feature Request] Ability to delete branch after merge of PR

### ISSUE THREAD

**Issue by camalot** [slapperwan/gh4a#329]
After I merge a PR in to the branch, there should be an option for me to delete that source branch if it is not protected.

**Comment by Tunous** [comment]
[This](https://developer.github.com/v3/git/refs/#delete-a-reference) seems to be the API for this.

**Comment by Tunous** [comment]
Any ideas where this button could be located? I think that the best option would be inside of pull request content header (under branches) but I'm not sure.

**Comment by camalot** [comment]
I would say, either where the "merge button" is, after it is merged, or at the bottom of the activity of the PR.

**Comment by Tunous** [comment]
I don't like locating it where the merge button is. If we place it here then it will be either hidden under 3 dots menu or will need an icon (that's not a common action so it would be hard to recognize it).

Placing it at the bottom is nice but I also wanted to add restore branch button once deleted. This could be problematic since restoring is less common and the button would just disturb with commenting if there is some more activity after that. 

I can think of another option:
Display delete branch button together with merged event and restore branch button together with latest branch deleted event. This needs displaying branch restored and deleted events but I think they are already possible to get with API (not sure).
