### ISSUE TITLE
Tapping an item in My Issues looks for Pull Request

### ISSUE THREAD

**Issue by akwala** [slapperwan/gh4a#347]
After getting the list of My Issues, if an item (e.g. issue #999) from the list is tapped, the search fails with a message saying Pull Request #999 wasn't found. The app is apparently searching for a Pull Request instead of an Issue.

**Comment by akwala** [comment]
... I saw this behavior in the Created list of My Issues.

**Comment by maniac103** [comment]
Couple of questions:
- what version of Octodroid is this?
- what's the issue in question (if in a public repo)?
- got a screenshot of the precise message?

**Comment by akwala** [comment]
@maniac103 Octodroid version 3.8.1

I just reproduced the behavior on this very issue, i.e., issue #347 of slapperwan/gh4a.

**Comment by maniac103** [comment]
This is an issue involving changed Github API behavior and app misbehavior. The app used to target Github's 'beta' endpoint, which changed behavior: Previously it would not send a 'pull_request' field for issues, now it sends a dummy 'pull_request' field. The app only checks for the field's existence though, which is why it broke over time.
However, newer Octodroid versions work fine as they don't target the beta endpoint anymore, so this is already fixed.
