### ISSUE TITLE
Pull requests do not show comments count

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#472]
When viewing them through "My repositories" they work correctly but when going to see pull requests of a repository then that information is not displayed.

**Comment by maniac103** [comment]
I assume you mean 'My pull requests', no 'my repositories'? And the second case is repository overview -> Pulls?

**Comment by Tunous** [comment]
Ah yeah that's what I meant, sorry .

**Comment by maniac103** [comment]
I'm pretty sure that's a shortcoming of the API and not all fields of the PRs in the list are filled in the latter case. I'll check it though.

**Comment by maniac103** [comment]
The issue is that the 'my pull requests' list actually lists issues [1], [2] and the PR list returns pull requests [3], [4]. The latter API doesn't include comment counts for whatever reason :(

[1] https://api.github.com/search/issues?q=is:pr%20state:open%20repo:slapperwan/gh4a
[2] https://developer.github.com/v3/search/#search-issues
[3] https://api.github.com/repos/slapperwan/gh4a/pulls
[4] https://developer.github.com/v3/pulls/#list-pull-requests
