### ISSUE TITLE
A Path with wildcard incorrectly turns on comment highlighting

### ISSUE THREAD

**Issue by vwal** [slapperwan/gh4a#503]
See a file in my repository: https://github.com/vwal/cryptovault/blob/master/create-crypto

Around line 625 there's a path that ends with a wildcard: ".../*". This turns on comment highlighting (all gray) for the remainder of the file.

**Comment by vwal** [comment]
I suppose Octodroid would need to be language aware to fix this. Since the mentioned repository is a bash script, for a workaround I added the following comment in the end of the line with the wildcard: `# */`. This closes the comment and prevents it from flowing through the rest of the file.

**Comment by maniac103** [comment]
The problem is that file type is determined by file extension. If you named it with the extension .sh, syntax highlighting likely would be fine. If the extension isn't known or not present, prettify (which is what we're using for highlighting) switches to some kind of universal mode which also recognizes C syntax and thus interprets /* as start of a multiline comment.

**Comment by vwal** [comment]
I changed the extension to `.sh` as you suggested, and now the syntax highlighting works. Thanks!
