### ISSUE TITLE
Images take long time to load

### ISSUE THREAD

**Issue by viktorstrate** [slapperwan/gh4a#661]
Some repositories, with many of images in their readme file, take up to a minute to load, with a decent internet speed. It is so slow, I somtimes open the repository in a browser, just because the images will load faster.

**Comment by Tunous** [comment]
The problem is with https://github.com/slapperwan/gh4a/blob/master/app/src/main/java/com/gh4a/fragment/RepositoryFragment.java#L343 which calls https://github.com/slapperwan/gh4a/blob/master/app/src/main/java/com/gh4a/utils/HttpImageGetter.java#L393.

It's all executed in a single task and updates the text only after all images are loaded. This means that the more the images in a file the longer it will take to load. This is more problematic when viewing files in the file viewer as there the images will delay displaying of the whole file contents.

Example file I found that takes a longer while to open: https://github.com/google/flexbox-layout/blob/master/README.md

**Comment by MattiaPrimavera** [comment]
any particular reason not to replace **AsyncTask** with **Picasso** library async image loading from a web url functionality on this one ?

**Comment by maniac103** [comment]
Yes. After each image load, the HTML content of the readme file needs to be rendered to a format that can be displayed in a TextView again. Doing this after each image would be very inefficient.

**Comment by Tunous** [comment]
Then something else must be slowing that file viewer because my example took much longer to load than other files. (Probably because it's big?)

For the TextView wouldn't it be possible to use layered drawables? (Initially set to layer with loading icon and after load switched to layer with image.) I saw examples of that on stack overflow before. That way it would be still rendered only once and we could use Picasso to do the actual loading of each image separately.

Sadly looking at the current code it'll require a fair bit of rewriting to get it working...

**Comment by MattiaPrimavera** [comment]
@maniac103 if I correctly understood, that means **all the images are downloaded** before the placeholders gets replaced **all at once**, right ?

**Comment by maniac103** [comment]
@MattiaPrimavera Right, exactly that.
