### ISSUE TITLE
Remember last open view and inputs

### ISSUE THREAD

**Issue by jancborchardt** [slapperwan/gh4a#704]
Sometimes I get the error "OctoDroid quit unexpectedly" or similar.

While that would also be good to fix, the main issue is
- The last open issue is not remembered. If you were in an issue from unread notifications, that issue will now be read, not shown in the list anymore and difficult to retrieve back.
- The content of a comment, if you wrote anything yet, will be lost.

It would be great to handle possible errors more gracefully by remembering that: the last state and the input.

**Comment by Tunous** [comment]
The second point is already being discussed in #358.

As for the first point, It's an interesting approach but I don't think it can be done in a user-friendly way. I can't think of a single application that would be doing this. It's better if you just try to find why these crashes happen. (Version of the app, Android might take effect so it's worth to list them when reporting)

**Comment by maniac103** [comment]
Remembering the app's state during crashes really doesn't sound like something we should heavily invest time in; the time indeed seems better spent in fixing those crashes.

@Tunous I'll add you to the fabric.io organization in case you want to look over the crash reports as well.

@jancborchardt Given you're an Android developer as well, it would be great if you could open issues with Logcat output for those crashes. Thanks.

@slapperwan I fixed the most frequent crashes since 4.2.0 already, so if we could do a 4.2.1 soon-ish, that'd be great.

**Comment by Tunous** [comment]
@maniac103 My email on fabric is "thanel dot app@gmail dot com" (replace " dot " with ".")

**Comment by maniac103** [comment]
@Tunous Thanks, invite sent.

**Comment by Tunous** [comment]
@maniac103 I think that didn't work. 
Here is my email again : https://gist.github.com/Tunous/ba79bdb377196845f029bf8dc1b0f6e6

**Comment by Tunous** [comment]
Got it now, thanks.

**Comment by Tunous** [comment]
Closing because decision was made for first point and second is a duplicate.
