### ISSUE TITLE
Use Butterknife

### ISSUE THREAD

**Issue by MattiaPrimavera** [slapperwan/gh4a#713]
This would eliminate the need for **findViewById** call and reduce **boilerplate code** sometimes for event listeners

**Comment by smichel17** [comment]
And while we're at it, why not just switch to kotlin and get all this stuff basically for free? :P

**Comment by MattiaPrimavera** [comment]
@smichel17 you're contribution was indeed fundamental, that's why :P 

On **kotlin** well, it is maybe still soon for the community to be largely adopted in open source projects?

**Comment by smichel17** [comment]
I've been using it for just over a year without any major issues. And since it compiles to jvm bytecode you can rewrite class by class. Plus, there's an automatic conversion tool from java to (usually) functionally correct, if not idiomatic, kotlin.

The only downside I can think of is that it can be difficult to go back if you start using a feature that's in kotlin but not java -- but that's true of using a library as well.

**Comment by maniac103** [comment]
Nope, I've considered it before, but I strongly dislike the magic that comes with it. IMHO, the more obvious the code is, the better it is, and butterknife replaces one-line findViewById calls by one-line annotations, so it's not worth introducing the magic IMHO.
