### ISSUE TITLE
API rate limit

### ISSUE THREAD

**Issue by MattiaPrimavera** [slapperwan/gh4a#717]
I get the following often pretty soon when developing ... 

```
API rate limit exceeded for IP_ADDRESS. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) (403)
                                                org.eclipse.egit.github.core.client.RequestException: API rate limit exceeded for IP_ADDRESS. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) (403)
``` 

The documentation reports the following:  

> Increasing the unauthenticated rate limit for OAuth applications
If your OAuth application needs to make unauthenticated calls with a higher rate limit, you can pass your app's client ID and secret as part of the query string.

``` bash
curl -i 'https://api.github.com/users/whatever?client_id=xxxx&client_secret=yyyy'
HTTP/1.1 200 OK
Date: Mon, 01 Jul 2013 17:27:06 GMT
Status: 200 OK
X-RateLimit-Limit: 5000 # Instead of 60
X-RateLimit-Remaining: 4966
X-RateLimit-Reset: 1372700873
``` 

Did i miss anything ?

**Comment by Tunous** [comment]
Are you logged in?

**Comment by maniac103** [comment]
Probably not. His point likely is that we should amend client ID and secret to the API calls if we're not logged in ... I'm not sure whether I'm a fan of that :-/

**Comment by MattiaPrimavera** [comment]
Well that could help testing the app without login if not needed ... the real problem here is I get redirected to the browser github authorization page, but the green button to authorize Octodroid_dev access to my account is disabled ... Sorry for the question, but should I need special rights for it ?

**Comment by Tunous** [comment]
Did you register application correctly as described in readme?

**Comment by MattiaPrimavera** [comment]
apparently the issue is occurring within the emulator only :S, works on real device ...

**Comment by smichel17** [comment]
@MattiaPrimavera I had the same issue and it's a problem with the webview. Download firefox and it'll work fine. (Note: firefox klar will not work since it renders the page with the system webview)

**Comment by notramo** [comment]
On the oauth page, the green button is enabled only if you have read all things that the app will have access to. But the categories can't be expanded, because webview has a bug.
I havent got firefox installed, so here's my solution:

- i logged in with the browser on the phone, it saved cookies
- sent the uri to my desktop
- logged in on desktop, expanded the categories of permissions
- went back to the phone, and authorized again

A notification should be added to this app that informs the user about the webiew bug, and gives him possible solutions.

**Comment by Fs00** [comment]
To get a higher rate limit for unauthenticated requests, nowadays the client ID and client secret need to be passed [via basic authentication header](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#oauth2-keysecret) (and not via query parameters anymore).
Since that doesn't seem to be an insecure way to send those credentials, would you accept a PR to implement it @maniac103?

**Comment by maniac103** [comment]
Sure, it's not exactly secure, but not any more than using query parameters.
