### ISSUE TITLE
Is OctoDroid dead?

### ISSUE THREAD

**Issue by dimqua** [slapperwan/gh4a#867]
:*-(

**Comment by gregsdennis** [comment]
I'm using FastHub now.  I liked Octo, but I haven't seen an update in quite some time, and now some things seem to be broken for me like reactions and comments on PRs.

**Comment by maniac103** [comment]
Both this comment and the reaction to your comment were added via Octodroid, so I'm not sure what exactly is broken there? Additionally, did I miss an issue report? ;-)

Octodroid isn't dead as in 'I don't care about it anymore', I'm rather so constrained on time so that I'll just try to keep it working for now instead of adding new features. I'm still using it myself after all, as I don't like Fasthub's UI.
